name: Update Dependencies
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 6 * * *"
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: false
          submodules: true
          clean: false
          fetch-depth: 0
          #persist-credentials: false
      - name: "Import bot's GPG key for signing commits"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ACTION_COMMIT_SING_PRIVATE_KEY }}
          passphrase: ${{ secrets.ACTION_COMMIT_SING_PASS }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Extract commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update submodules
        id: mod
        run: |
          git config --global user.name "Madman10K"
          git config --global user.email "contact@madladsquad.com"
          git fetch --all
          git checkout master || git checkout -b master
          ./sanitize-official.py
          ./sanitize-community.py
      - name: Commit
        id: commit
        run: |
          (git add . && git commit -m "Sanitize files" && git push origin master && echo "com=+" >> $GITHUB_OUTPUT) || echo "com=?" >> $GITHUB_OUTPUT
